name: ci
on:
  push:
jobs:
  release:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: init
        run: make init
      - name: test
        run: make testing
      - name: build
        run: make build
